#!/bin/bash

FILENAME=/var/log/server/deploy-`date +%Y%m%d%H%M`.log


/home/arsen/Builds/AndroidServer/install/server stop >> $FILENAME 2>&1
/home/arsen/Builds/AndroidServer/install/deploy  >> $FILENAME 2>&1
/home/arsen/Builds/AndroidServer/install/server start  >> $FILENAME 2>&1
